# Generated by Django 4.2.13 on 2024-06-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_voted',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_most_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 15, 3, 35, 122807, tzinfo=datetime.timezone.utc), verbose_name='due date'),
        ),
    ]
